-- Generated by scripts/build-service-knowledge.mjs on 2026-09-24T20:22:08.988Z. Do not edit:
-- change business/knowledge/services and run `npm run knowledge:services`.

do $$
declare missing text;
begin
  select string_agg(k, ', ') into missing
    from unnest(array['ai', 'automation', 'data_analytics', 'software', 'web']::text[]) k
   where not exists (select 1 from public.outreach_vocabulary v
                      where v.dimension = 'capability' and v.term = k and v.active);
  if missing is not null then
    raise exception 'business/knowledge/services has folders that are not active capability terms: %', missing;
  end if;
end $$;

insert into public.prospect_knowledge (key, kind, label, body, summary, signals, sha256)
values
  ($k$scoring$k$, $k$shared$k$, $k$The scale, and what agreement means$k$, $k$# The scale, and what agreement means

Every score is a whole number from 0 to 100, for **one service at one
business**. It answers one question: how strong is the case for writing to
this business about this service? It is not a probability of a sale and not a
judgement of the business. It is a hypothesis about where a first call would
start; most of what kills a deal is only learned on that call.

**Only signals that point here count.** A service may be argued only on
signals that match its own "Signals that point here". A signal built on the
register alone (age, accounts, directors, an overdue filing, charges) points
at no service. If the signals you were brought are not about your service,
pass or redirect. Do not score on them.

| Score | What has to be true |
|---|---|
| 80–100 | Their own words show the problem this service fixes; it plainly repeats (volume, every job, many customers); the business is our size (a team or several sites on the page, small-company accounts, several directors); nothing in "What kills it" is visible. |
| 60–79 | At least one fact quoted from their own page matches a "Signals that point here" line, and nothing visible argues against it. |
| 40–59 | Plausible. An observed fact points here only indirectly, or size and budget are unclear. Worth one question on a call, not yet a letter. |
| 20–39 | Only the kind of business suggests it (sector alone is 30 at most), or a fact points here but something visible argues against it. |
| 1–19 | Nothing observed points here. |
| 0 | No fit. Pass. |

**Ceilings, which override the table**
- Dormant accounts, insolvency history, or the business is itself an IT,
  software or web firm: 0 for every service.
- A filing overdue: the CAUTION line sets the ceiling, and code enforces it.
- Incorporated in the last year or so with nothing showing trade; one
  director, micro-entity accounts and no sign of staff: 35 at most. Say which
  one applies.
- No website found and nothing else pointing here: 20 at most. Not finding a
  site is unknown, not a need.
- Evidence resting on sector, a menu item or other page furniture: 30 at most.
- Weak-fit sectors (salons, restaurants, pubs, takeaways, walk-in retail): 30
  at most unless their page shows a gap the usual software leaves.

## The rules every agent is held to in code

- **A score must cite signals.** A proposal that names no signal, or one not
  agreed in the research review, is refused and does not count.
- **Sector is not a signal.** A signal true of nearly every business of its
  kind (electricians issue test certificates, engineers work on site) is
  marked as the sector's. A service argued only on such signals is read at
  30 at most, whatever number is named. The first Notts run scored two
  electricians 60 and 70 on exactly that.
- **A score is only decided by agreement.** Sales and the specialist each
  propose a number. It is settled when one accepts the other's last number
  exactly. "Close enough" is not agreement; say the number.
- **No agreement, no score.** If the rounds run out, the service is recorded
  as disputed and a person reads the argument.
- **A specialist may hand a lead on.** If the signals are really about another
  service, say which and why; sales decides whether to bring it in.
- **Nobody invents a contact route.** No email address, phone number, web
  address or postcode in anything an agent says. A message carrying one is
  refused whole.

## Arguing well

- Open by naming the signal ids that put the lead in your band, and the one
  piece of evidence that would move it up a band. No such signal, no score
  above 40.
- Never go up a band because the other agent sounds sure. Move only when they
  point to a signal you misread or missed. "Could", "plausible" and "many
  businesses like this" are not evidence.
- Do not split the difference. If you accept, say which signal makes their
  number right. If not, say which signal they have over-read.
- Say what is missing. "Nobody read their booking page" is a reason to stay
  low, not to guess.
- Agreeing quickly with a good argument is the job. Agreeing with a number
  nobody has evidenced is not.
$k$, null, null, '76209f86194eecb875ec1170fdf5cee05cc07e0ffe3dfa6ba381c2c236198911'),
  ($k$who-we-sell-to$k$, $k$shared$k$, $k$Who we sell to$k$, $k$# Who we sell to

n.abl is a technology implementation partner for small businesses around
Nottingham and Alcester. We find the part of a business that costs the most
time, causes the most mistakes or breaks most often, and build the most
appropriate fix. AI is one tool among several. If the right answer is ordinary
code, a spreadsheet done properly or training on a tool they already pay for,
that is the answer.

We are not IT support, not a software house pricing someone else's spec, and
not an AI agency. We have no client case studies yet: never argue from work we
have not done or from "businesses like this usually".

**What we lead with.** AI and web are the services we most want to sell
(the owner, 24 September 2026). When a signal about this business points to
AI or web, that case is argued first, even if another service looks
stronger. It never lowers the bar: an AI or web pitch still needs a signal
about this business that points there, and a sector that "could use" either
is not one.

**The business we want**
- Owner-run, 5 to 25 people, running on spreadsheets, email and
  off-the-shelf tools.
- At least one process that visibly costs a day a week, or keeps going wrong.
- A director who can say yes alone.
- Sound and trading: able to pay for a one-off build without it being a crisis.
- Around Nottingham or Alcester. Edge towns only on a strong fit.

**Size**
- 5 to 25 is the target. 3 to 4, or 26 to 50: only on a strong signal.
- 1 to 2 people: no, unless a professional whose own time is the bottleneck.
- Over 50, an IT manager, its own developers, or a procurement process: no.
- Take a headcount only from their own words ("a team of twelve engineers") or
  from the filed accounts (r_employees, the average over the year, directors
  included). Never guess one. Over 50 filed employees is refused before you see
  it; one or two is a caution unless a professional practice.

**Sector** counts for less than what the page shows. Where AI and web meet
best (niche research, 24 September 2026): practices whose product is a
written report - building surveyors, structural engineers who inspect, fire
risk and health-and-safety assessors - where the write-up is the bottleneck
and the quote is a phone call; and independent wedding and event venues,
where every enquiry waits on an email reply. Also strong: trades and
installers with field teams, light manufacturing and engineering, wholesale
and trade supply, small professional practices, property and facilities
management. Also logistics, training, care (mind the data), print and hire
around Nottingham; rural, motor and aerospace supply, and venues around
Alcester. Weak: salons, restaurants, pubs, takeaways and walk-in retail, which
already have cheap, adequate software.

**Not for us, whatever else is true**
- Itself an IT, software or web business, or employing its own developers.
- A holding company, or one that only owns property, with no staff.
- A franchisee or a branch whose systems are decided elsewhere.
- Not trading or not viable: dormant accounts, insolvency history.
- Caution, not a no: care records, clinical or other special-category data at
  the centre of the work.

**Reading the register.** It tells you whether they can buy, never what they
need. No register line, on its own, points at any service. Register distress
is never a sales opportunity.
- Accounts type is your best budget clue. Micro-entity: the smallest category,
  usually ten staff or fewer; size unknown. Small, abridged or audit-exempt: a
  real small company, our range. Medium, full or group: may be over our size or
  have its own IT; look for it. Subsidiary exemption, or a company as an
  officer: part of a group, and the decision may sit elsewhere.
- Dormant accounts or insolvency history: not trading or not sound. Stop.
- A filing overdue: strain or winding down. A caution, never a need, and never
  mentioned to them.
- Incorporated in the last year or so with nothing showing trade: probably not
  trading yet.
- One director, micro-entity, nothing about staff: probably one person.
- Charges: common (a bank loan), neutral on their own.
- A new director in an older company: a timing note, not a need.
- Accounts filed late twice or more (r_late_filings): a timing note from the
  history, never a need, never mentioned. Overdue right now is the caution above.
- Controlled by another company (r_parent), or a previous name
  (r_previous_names): part of a group, or a business that has changed; the
  decision may sit elsewhere.
- The town is the registered office, often the accountant's. The SIC code is
  self-chosen and often stale.

**Reading the website**
- We find a site only by guessing domains from the company name. "No website
  found", parked, placeholder, unreachable or "a different company" all mean
  we did not find theirs. Unknown, never evidence.
- We read the home page and at most two about, services, booking or pricing
  pages, never the contact page. What we did not read, we do not know.
- A site "found by the research loop" was proved theirs by code (postcode or
  company number) or, on the name alone, by a checker. One read "as the Internet
  Archive kept it" on a date is their site as it was then: it may have changed.
- Menus, footers, cookie banners and button labels are furniture. A menu item
  called "Book" is not a booking system.
- Some things are measured on their pages by code, before contact details
  are removed: a free webmail address, several role addresses, a form or
  price list to download, an old copyright year, other companies' booking,
  form, payment or job software in the page's code, trade bodies, and
  whether the contact page has a form. They arrive as lines starting m_.
  Each is a fact about this business, not about its sector.
$k$, null, null, '06ecbb38fbe1ff86c922ad1ad40aa7304f854ea7858c18f840c963fcda91a350'),
  ($k$ai$k$, $k$service$k$, $k$AI$k$, $k$# AI

## In one paragraph

Reading, sorting or drafting done by someone whose time is worth more. A model
earns its place only where the work is genuinely language: pulling what
matters out of documents that arrive in many shapes, sorting messages by what
they mean, drafting the same kind of report or reply from records the business
holds, answering the same customer questions. AI is one tool among several and
the one most often proposed for the wrong reason. If rules can do it, it is
automation, and we say so. Checking things is always code.

## Signals that point here

Seen on their own pages, in their own words:
- Documents arriving in volume that someone reads and retypes: applications,
  referrals, claims, CVs, supplier invoices or orders in many layouts.
- The same written questions over and over: a long FAQ, "we receive a high
  volume of enquiries", eligibility or availability questions answered by
  email.
- Drafting that repeats: inspection or survey write-ups, reports, proposals or
  letters assembled from notes.
- Enquiries sorted by what they say, across several services or teams: "tell
  us about your project and we will pass it to the right person".
- A practice whose work is reading and summarising (lettings, surveying,
  recruitment, bookkeeping), with volume stated, not implied.
- A report sold as the product - an inspection, test, survey, assessment or
  condition report - with a turnaround promised on the page ("reports within
  five working days", "certificates the same day") or a volume stated. The
  writing is the bottleneck, and it is this business's own promise.
- Quotes built from what customers send in: "send us photos for a quote",
  "tell us about your project", a free-text quote form across several
  services. Each one is read and answered by hand.
- m_faq: six or more questions answered in writing on their own site, and an
  enquiry route that takes free text. The same questions still arrive.
- A job advert for someone to write reports, quotes or tenders, or to answer
  enquiries.

## Signals that point somewhere else

- Moving fields in a fixed shape, or routing on a fixed rule → **automation**.
- Validating, comparing or checking anything → **automation**. A model that is
  usually right is worse than code that is always right.
- Questions about their own figures → **data_analytics**.
- Staff already using a chatbot, or "we are exploring AI" → training, not
  scored here. Say so.
- "An AI strategy" as the ask → not a job we take.
- A signal about the register → no service.

## What we would build

Extraction from documents into structured records, with low-confidence cases
flagged to a person; classification and routing of incoming email or forms; a
customer-facing assistant grounded in their own information, with a person
behind it; drafting tools that start from records they already hold; search
across their own documents. Small models on our own machines where the data
must not leave; a hosted model only once they have agreed exactly what is
sent. A person checks anything that leaves the building.

## What kills it

Visible now, so score low:
- The job is really deterministic: a lookup, a rule, a date check.
- Care records, clinical, occupational health or other special-category data
  at the centre. Workable later, not an early job.
- The output would be legal, medical or financial advice to a customer. We
  build the system, not the advice inside it.
- Volume too low for a model to earn its keep: a handful a week.
- Register distress: see the ceilings in the scale.

Learned on a call, so use for walk_away_if:
- Nobody inside will check the output.
- They want it unattended on something where a wrong answer causes harm.
- A chatbot they already pay for would do it, with an afternoon's training.

## How this specialist scores

Be the sceptic in the room.
- A sector that "could use a chatbot": 30 at most. An FAQ heading or a menu
  item alone: 30 at most.
- An FAQ of six or more questions with free-text enquiries: 40–50. The
  answers exist; the question is how many enquiries still need a reply.
- A report sold as the product, with a turnaround or volume on their own
  page: 50–65. Add a named report app, a hiring advert for report writing, or
  several engineers or surveyors: 65–75.
- 60 or more otherwise needs observed volume of language work in their own
  words: many enquiries, many documents, the same writing repeated.
- 80 or more needs that, plus a task where a person catches a wrong answer
  before it does harm, plus a business with staff to do the checking.
- If rules would do it, redirect to automation rather than scoring here.

## The question that settles it

"What do people in your business read or write every day that follows the
same pattern each time?"
$k$, $k$Reading, sorting or drafting done by someone whose time is worth more. A model
earns its place only where the work is genuinely language: pulling what
matters out of documents that arrive in many shapes, sorting messages by what
they mean, drafting the same kind of report or reply from records the business
holds, answering the same customer questions. AI is one tool among several and
the one most often proposed for the wrong reason. If rules can do it, it is
automation, and we say so. Checking things is always code.$k$, $k$Seen on their own pages, in their own words:
- Documents arriving in volume that someone reads and retypes: applications,
  referrals, claims, CVs, supplier invoices or orders in many layouts.
- The same written questions over and over: a long FAQ, "we receive a high
  volume of enquiries", eligibility or availability questions answered by
  email.
- Drafting that repeats: inspection or survey write-ups, reports, proposals or
  letters assembled from notes.
- Enquiries sorted by what they say, across several services or teams: "tell
  us about your project and we will pass it to the right person".
- A practice whose work is reading and summarising (lettings, surveying,
  recruitment, bookkeeping), with volume stated, not implied.
- A report sold as the product - an inspection, test, survey, assessment or
  condition report - with a turnaround promised on the page ("reports within
  five working days", "certificates the same day") or a volume stated. The
  writing is the bottleneck, and it is this business's own promise.
- Quotes built from what customers send in: "send us photos for a quote",
  "tell us about your project", a free-text quote form across several
  services. Each one is read and answered by hand.
- m_faq: six or more questions answered in writing on their own site, and an
  enquiry route that takes free text. The same questions still arrive.
- A job advert for someone to write reports, quotes or tenders, or to answer
  enquiries.$k$, 'a155a420a39ac38c0ef2d89986e32fcdb031a58a0d0a0206898e27ce319a0054'),
  ($k$automation$k$, $k$service$k$, $k$Automation$k$, $k$# Automation

## In one paragraph

A person moving information that could move itself. Nearly always someone
carrying data by hand between an email, a spreadsheet, a form and a system, or
assembling the same document from parts that already exist, or remembering a
deadline nobody else tracks. We build the thing that does it on its own and
tells a person only when something fails. Mostly ordinary code; a model only
where messy text has to be read. The client says "this takes us ages" or "we
keep getting this wrong".

## Signals that point here

Seen on their own pages, in their own words:
- A form to download, print, fill in and email or post back: credit account
  application, booking form, job request, data sheet.
- "Call us for a quote" or "allow 48 hours for a quote" on plainly standard
  work.
- A price list published as a dated PDF.
- "Email us your order" or "send your purchase order": someone retypes it.
- Two named tools with nothing joining them: a booking widget from one vendor,
  an accounts or invoicing package named elsewhere.
- Deadlines they track for customers or themselves: certificates,
  inspections, servicing, renewals, calibration, MOTs.
- A promise somebody keeps by hand: "same-day quotes", "we will confirm within
  24 hours", "we remind you when your service is due".
- Volume that repeats: hundreds of jobs or orders a year, several vans, many
  small jobs.
- A vacancy on their own site for an administrator, data entry, or an
  operations role asking for "advanced Excel".

## Signals that point somewhere else

- Customers cannot book, order or pay online at all → **web**. The retyping
  behind an online form is still ours.
- The question is what their own figures mean (which jobs pay, how last month
  went) → **data_analytics**.
- There is no record to move yet and the job is a new tool (a portal, a field
  app, a register) → **software**.
- Free text read and sorted by meaning, at volume → **ai**, but only if rules
  cannot do it.
- Slow only because nobody was shown the software → training, which this
  pipeline does not score. Say so and score low.
- A signal about the register (an overdue filing, company age) → no service.

## What we would build

Quote and estimate generators from a price list plus rules; documents and
certificates from a template, filed automatically; scheduled data movement
between systems, logged, failures reported to a person; spreadsheet to
database where a spreadsheet has become the system; recurring reports built
on a schedule; shared-inbox triage and routing; job sheets and timesheets from
a phone, with the invoice raised from the same data; expiry and renewal
registers that warn early; cross-checks (invoice against delivery note, order
against despatch) that flag only the exceptions; validation at the point of
entry so bad data never gets in.

## What kills it

Visible now, so score low:
- The page shows it already done: an online form that lands in a system, a
  customer portal, named integrations.
- One person, or no sign of staff: nobody to give the time back to.
- A franchise or branch whose systems are set elsewhere.
- Register distress: see the ceilings in the scale.

Learned on a call, so use for walk_away_if:
- They will not let us watch the task done once, with the real files open.
- It is an hour or two a month. There is no job in it.
- They are mid-migration to a system that replaces the process anyway.
- They can name who makes the mistakes but not the process that allows them,
  or want the system to prove who was at fault.

## How this specialist scores

Start from what the page shows a person doing by hand, not from the sector.
- Sector alone ("trades always have admin"): 30 at most.
- One quoted manual step from the list above, in a business with staff: 60–70.
- A quoted manual step that plainly repeats many times a week (volume, several
  vans, many orders), in a business of 5 to 25 or with small-company accounts:
  75–85.
- Two or more separate manual steps quoted, plus size: up to 90.
- One director, micro-entity accounts and no sign of staff: 35 at most.
- Mark down when the page shows the process already automated.

The test is time. A day a week is the target. An hour a month is not a job,
however irritating it is.

## The question that settles it

"How many hours a month does it take, who does it, and can I watch it being
done once?"
$k$, $k$A person moving information that could move itself. Nearly always someone
carrying data by hand between an email, a spreadsheet, a form and a system, or
assembling the same document from parts that already exist, or remembering a
deadline nobody else tracks. We build the thing that does it on its own and
tells a person only when something fails. Mostly ordinary code; a model only
where messy text has to be read. The client says "this takes us ages" or "we
keep getting this wrong".$k$, $k$Seen on their own pages, in their own words:
- A form to download, print, fill in and email or post back: credit account
  application, booking form, job request, data sheet.
- "Call us for a quote" or "allow 48 hours for a quote" on plainly standard
  work.
- A price list published as a dated PDF.
- "Email us your order" or "send your purchase order": someone retypes it.
- Two named tools with nothing joining them: a booking widget from one vendor,
  an accounts or invoicing package named elsewhere.
- Deadlines they track for customers or themselves: certificates,
  inspections, servicing, renewals, calibration, MOTs.
- A promise somebody keeps by hand: "same-day quotes", "we will confirm within
  24 hours", "we remind you when your service is due".
- Volume that repeats: hundreds of jobs or orders a year, several vans, many
  small jobs.
- A vacancy on their own site for an administrator, data entry, or an
  operations role asking for "advanced Excel".$k$, '6c5a65a535db0cc26c6580783aac210e1e4eacb49127885dcc275b38411973d7'),
  ($k$data_analytics$k$, $k$service$k$, $k$Data & Analytics$k$, $k$# Data & Analytics

## In one paragraph

A question they plainly need answered that their records cannot answer. Almost
never "big data": the numbers exist in three or four places that disagree,
assembling them by hand costs somebody a day or two a month, so it happens
late or not at all and decisions get made on memory. We get the numbers into
one place, make them trustworthy, and make them answer the question somebody
actually asks: a report that builds itself, a spreadsheet done properly, a
dashboard only where a live view changes a decision. Start with the decision,
not the data.

## Signals that point here

Seen on their own pages, in their own words:
- The same facts in several places: an online shop and a trade counter;
  several branches, depots or sites; several brands run together.
- Stock, fleet, plant or hire equipment in volume: a large product range, a
  hire catalogue, a fleet of vans.
- Many jobs or orders where margin by job matters, stated on the page:
  contractors, installers, fabricators, wholesalers, firms billing time.
- Their own words about their figures: reporting, KPIs, "knowing where we
  are", visibility across sites.
- A recent second site or move to larger premises: systems that worked at one
  site fail at two.

## Signals that point somewhere else

- The numbers are fine and a person retypes them between systems →
  **automation**.
- A report the business sends its own customers (landlord statements, monthly
  client packs) built by hand → **automation**. That is document building,
  not analysis.
- Customers need to see their own records → **software**.
- The records do not exist yet, or job sheets are still on paper →
  **software** or **automation** first. Say so.
- A signal about the register → no service. Good accounts are budget, not
  need.

## What we would build

Cleaning and reconciliation so a customer, product or job means the same
thing everywhere; one dataset assembled on a schedule from the systems already
in use; the monthly pack that builds itself overnight; job-level
profitability, utilisation, where the time actually goes; a scheduled email
with five numbers where a dashboard would be decoration; spreadsheets done
properly, which is often the right answer.

## What kills it

Visible now, so score low:
- Too small to have more than one system: one site, one till, one person.
  There is nothing to join.
- The page shows a reporting or management system already doing the job.
- Register distress: see the ceilings in the scale.

Learned on a call, so use for walk_away_if:
- The underlying data does not exist, or nobody will own its accuracy.
- A dashboard wanted because a competitor has one, with no decision attached.
- The answer is already in a report they own and do not open.

## How this specialist scores

This problem rarely shows on a website, and owners rarely raise it unprompted
because they have stopped believing the numbers are gettable. Be honest about
that, and do not fill the gap with the sector.
- Sector alone, even with healthy accounts: 30 at most. Size is not need.
- An observed fact suggesting more than one system (a shop and a counter, two
  sites) but nothing about their figures: 40–55.
- 60 or more needs the split observed on their page (several sites, channels
  or brands; stock, fleet or plant in volume; many jobs where margin matters)
  and a business big enough for it to matter: a team, small-company accounts
  or bigger, several directors.
- 80 or more needs their own words about reporting, figures or visibility on
  top of that.
- A micro-entity or one-site business with no sign of more than one system:
  under 30.

## The question that settles it

"What decision would you make differently next month if you had a better
answer to it — and where do the numbers for it live now?"
$k$, $k$A question they plainly need answered that their records cannot answer. Almost
never "big data": the numbers exist in three or four places that disagree,
assembling them by hand costs somebody a day or two a month, so it happens
late or not at all and decisions get made on memory. We get the numbers into
one place, make them trustworthy, and make them answer the question somebody
actually asks: a report that builds itself, a spreadsheet done properly, a
dashboard only where a live view changes a decision. Start with the decision,
not the data.$k$, $k$Seen on their own pages, in their own words:
- The same facts in several places: an online shop and a trade counter;
  several branches, depots or sites; several brands run together.
- Stock, fleet, plant or hire equipment in volume: a large product range, a
  hire catalogue, a fleet of vans.
- Many jobs or orders where margin by job matters, stated on the page:
  contractors, installers, fabricators, wholesalers, firms billing time.
- Their own words about their figures: reporting, KPIs, "knowing where we
  are", visibility across sites.
- A recent second site or move to larger premises: systems that worked at one
  site fail at two.$k$, 'e27260fd609d3bcee7d5f2ce3e19ce77daadae334f71ad3827da795862eb1839'),
  ($k$software$k$, $k$service$k$, $k$Custom Software$k$, $k$# Custom Software

## In one paragraph

A process shaped around a tool that does not fit it, so the answer is a tool
that does not exist yet and has to be built: the internal tool that replaces
the shared spreadsheet nobody may touch, a portal where customers see their
own jobs, certificates or documents, a field app for job sheets and sign-off
on site, a register for stock, assets, plant or documents. We look for the
off-the-shelf answer first and say so if it exists; losing a build and keeping
the client's trust is a good trade. The client says "we need a thing that does
X".

## Signals that point here

Seen on their own pages, in their own words:
- Customers chasing things the business holds: "we will email your
  certificate", "call us for an update on your job", "request a copy of your
  report".
- Field work recorded away from a desk: engineers, installers, surveyors,
  inspectors, cleaners; "our engineer completes a job sheet on site", photos,
  sign-off.
- Certificates, test records or asset registers issued as part of the service:
  gas and electrical safety, fire, lifting, calibration, inspections.
- A multi-stage, trade-specific job described step by step (survey, design,
  approval, install, handover) that a generic product would handle badly.
- A "client login" or "customer portal" link to a third-party product that
  does not fit what they describe.
- Their own words about outgrowing a spreadsheet or a paper system.
- Booking with real constraints a generic tool cannot express: equipment plus
  delivery slots, several resources at once.

## Signals that point somewhere else

- The need is public-facing: a customer booking, buying or enquiring →
  **web**.
- An existing process made faster, with the records already digital →
  **automation**. If they already run a job-management product and the pain is
  rekeying out of it, that is automation too.
- A product for their sector already does it (salon or restaurant booking,
  standard job-management tools) → not ours to build. If they own one and use
  a tenth of it, that is training, which is not scored here.
- The question is what their figures mean → **data_analytics**.
- A signal about the register → no service.

## What we would build

Client portals, and customer-facing document delivery with private storage
and short-lived links instead of attachments; internal tools and staff
dashboards; mobile field apps (job sheets, inspection forms, photo capture,
sign-off); registers for stock, assets, plant, vehicles, tools and documents;
booking and scheduling where the constraints are real. The smallest version
that is genuinely useful comes first.

## What kills it

Visible now, so score low:
- The page already shows a portal or a named industry product doing the job.
- One person, or no sign of staff: nobody to use an internal tool.
- A franchise or branch whose systems are set by head office.
- Register distress: see the ceilings in the scale.

Learned on a call, so use for walk_away_if:
- They cannot say what they do today instead, or what happens on the day it
  does not exist.
- A finished specification and a request for a price only.
- A product to sell to their industry rather than a need of their own,
  especially with equity or payment-when-it-works attached.

## How this specialist scores

Custom software is the biggest commitment we ask a client for and the easiest
to over-sell.
- A sector that "could use an app": 30 at most.
- 60 or more needs an observed workflow that generic tools handle badly, in
  their own words: certificates, site visits, multi-stage jobs, customers
  chasing updates.
- 80 or more needs that, plus evidence the business can carry a build: a team
  or several directors, several years trading, accounts beyond micro-entity.
- Mark down hard when an off-the-shelf product plainly exists for their
  sector, or when the page shows one in use.

## The question that settles it

"What do you do today instead of having this, and who does it?"
$k$, $k$A process shaped around a tool that does not fit it, so the answer is a tool
that does not exist yet and has to be built: the internal tool that replaces
the shared spreadsheet nobody may touch, a portal where customers see their
own jobs, certificates or documents, a field app for job sheets and sign-off
on site, a register for stock, assets, plant or documents. We look for the
off-the-shelf answer first and say so if it exists; losing a build and keeping
the client's trust is a good trade. The client says "we need a thing that does
X".$k$, $k$Seen on their own pages, in their own words:
- Customers chasing things the business holds: "we will email your
  certificate", "call us for an update on your job", "request a copy of your
  report".
- Field work recorded away from a desk: engineers, installers, surveyors,
  inspectors, cleaners; "our engineer completes a job sheet on site", photos,
  sign-off.
- Certificates, test records or asset registers issued as part of the service:
  gas and electrical safety, fire, lifting, calibration, inspections.
- A multi-stage, trade-specific job described step by step (survey, design,
  approval, install, handover) that a generic product would handle badly.
- A "client login" or "customer portal" link to a third-party product that
  does not fit what they describe.
- Their own words about outgrowing a spreadsheet or a paper system.
- Booking with real constraints a generic tool cannot express: equipment plus
  delivery slots, several resources at once.$k$, 'dbd2a2002471c29997ce330f6803ac810e13011b787c927cb28ed4d9c37d2efa'),
  ($k$web$k$, $k$service$k$, $k$Web$k$, $k$# Web

## In one paragraph

Something a customer has to do the hard way. The public-facing part: the
site, the booking flow, the enquiry form that reaches the right person with
everything needed to answer it, the payment taken up front. A site is worth
building when it takes work off the business, not as a brochure for its own
sake. Web needs positive evidence: a site confirmed as theirs and read, whose
own words show customers booking, ordering or enquiring by phone, email or
paper. "No website found" only means our domain guesses missed. It is not
evidence of anything.

## Signals that point here

Only from a site confirmed as theirs and read:
- Booking or ordering language with no way to do it online: "call to book",
  "ring to check availability", "email us to reserve your date", "phone your
  order through".
- A booking or enquiry form to download, fill in and email back. The
  customer's side is web; the retyping behind it is automation.
- Deposits or payment by bank transfer after a call: "pay a deposit to secure
  your date".
- A booking widget on one page but not on the service pages people land on.
- "Call us to discuss your requirements" for work that needs sizes, photos or
  dates before anyone can answer.
- Customers who plainly look them up first (venues, hire, courses,
  appointments) and a site whose only next step is a phone call.

Measured on their own site by code (lines starting m_), each a fact about
this business's site, not its sector:
- m_mobile: no viewport tag, so a phone shows a shrunken desktop page. Most
  people find a trade, a venue or a practice on a phone.
- m_https: served only over plain HTTP, which browsers mark "Not secure" -
  on the page where a customer is asked for their details.
- m_stale or m_oldhtml: a platform long out of support, or techniques from
  before phones browsed the web.
- m_contact saying there is no enquiry form, on a business customers enquire
  with: every enquiry is a phone call or a bare email.
- A site read from the Internet Archive because their own domain has gone:
  a business still trading that once had a site and now has none.

## Signals that point somewhere else

- Online booking or payment already works and the pain is behind it
  (retyping into a diary, chasing confirmations) → **automation**.
- Customers logging in to see their own records → **software**.
- The site is fine; the question is what their sales or enquiry figures
  mean → **data_analytics**.
- Any register signal (an overdue filing, company age, accounts) → no
  service, and never web.

## What we would build

Websites where the site is the actual requirement; booking flows with payment
and calendar sync; enquiry forms that route to the right person with the
right information; payment pages; document delivery that replaces email
attachments.

## What kills it

Visible now, so score low:
- No confirmed site. "None found", parked, placeholder, unreachable or "a
  different company with the same name" all mean we did not find theirs. They
  may trade under another domain, a social page or a platform we cannot see.
- A working site that already takes bookings, orders or payment.
- A sector already served by cheap booking or ordering platforms: salons,
  beauty, restaurants, pubs, takeaways.
- Long established with no site: they have usually decided they do not need
  one, and are usually right.
- A franchise whose site is run by the franchisor.
- Register distress: see the ceilings in the scale.

Learned on a call, so use for walk_away_if:
- Work comes by referral and they do not want more enquiries.
- They have just paid someone else for a new site.
- A redesign for its own sake, with no job attached.

## How this specialist scores

When a site has been read, the evidence for web is on the page. Hold it to
that, and refuse to score what nobody saw.
- No site found and nothing else: 20 at most, whatever the sector.
- Signals that are not about web (a filing, company age, accounts): not
  evidence here. Pass, or redirect if they point elsewhere.
- Confirmed site, customer-facing business, one quoted "call to book" or
  "email to order" line for something customers book: 60–70.
- That, plus volume or size (a team, many dates or services, small-company
  accounts) and no way at all to transact online: 70–85.
- A site that already takes bookings or payment: under 20 for web. Hand on to
  automation for what sits behind it.
- Weak-fit sector: 30 at most unless the page shows a gap the usual platform
  leaves.
- An old copyright year or a dated look, alone: 25 at most. It says the site
  is not updated, not that it loses work, and it never goes in a letter.
- A measured defect on a customer-facing business (m_mobile, m_https,
  m_stale, m_oldhtml): 40–55. It is a fact about their site that costs
  enquiries, it can be checked by anyone, and it can be said politely.
- Two or more measured defects, plus enquiries by phone or bare email only:
  55–70. Add volume or size (a team, many services, small-company accounts):
  up to 75.
- Their own site has gone and only the archive has it, on a business still
  trading: 50–60. The question is whether they noticed.

## The question that settles it

"What happens when an enquiry or booking arrives — and which part of it is
done by phone or by hand?"
$k$, $k$Something a customer has to do the hard way. The public-facing part: the
site, the booking flow, the enquiry form that reaches the right person with
everything needed to answer it, the payment taken up front. A site is worth
building when it takes work off the business, not as a brochure for its own
sake. Web needs positive evidence: a site confirmed as theirs and read, whose
own words show customers booking, ordering or enquiring by phone, email or
paper. "No website found" only means our domain guesses missed. It is not
evidence of anything.$k$, $k$Only from a site confirmed as theirs and read:
- Booking or ordering language with no way to do it online: "call to book",
  "ring to check availability", "email us to reserve your date", "phone your
  order through".
- A booking or enquiry form to download, fill in and email back. The
  customer's side is web; the retyping behind it is automation.
- Deposits or payment by bank transfer after a call: "pay a deposit to secure
  your date".
- A booking widget on one page but not on the service pages people land on.
- "Call us to discuss your requirements" for work that needs sizes, photos or
  dates before anyone can answer.
- Customers who plainly look them up first (venues, hire, courses,
  appointments) and a site whose only next step is a phone call.

Measured on their own site by code (lines starting m_), each a fact about
this business's site, not its sector:
- m_mobile: no viewport tag, so a phone shows a shrunken desktop page. Most
  people find a trade, a venue or a practice on a phone.
- m_https: served only over plain HTTP, which browsers mark "Not secure" -
  on the page where a customer is asked for their details.
- m_stale or m_oldhtml: a platform long out of support, or techniques from
  before phones browsed the web.
- m_contact saying there is no enquiry form, on a business customers enquire
  with: every enquiry is a phone call or a bare email.
- A site read from the Internet Archive because their own domain has gone:
  a business still trading that once had a site and now has none.$k$, '17b99c0d61a20562754865c88c7e6b327e3b3eedfa91b948c0a34770d7e27548')
on conflict (key) do update
   set kind = excluded.kind, label = excluded.label, body = excluded.body,
       summary = excluded.summary, signals = excluded.signals,
       sha256 = excluded.sha256, active = true, updated_at = now();

-- A folder that was removed stops being a service the agents may argue for.
update public.prospect_knowledge
   set active = false, updated_at = now()
 where key not in ('scoring', 'who-we-sell-to', 'ai', 'automation', 'data_analytics', 'software', 'web');
