-- Generated by scripts/build-service-knowledge.mjs on 2026-09-22T20:30:10.770Z. Do not edit:
-- change business/knowledge/services and run `npm run knowledge:services`.

do $$
declare missing text;
begin
  select string_agg(k, ', ') into missing
    from unnest(array['ai', 'automation', 'data_analytics', 'software', 'web']::text[]) k
   where not exists (select 1 from public.outreach_vocabulary v
                      where v.dimension = 'capability' and v.term = k and v.active);
  if missing is not null then
    raise exception 'business/knowledge/services has folders that are not active capability terms: %', missing;
  end if;
end $$;

insert into public.prospect_knowledge (key, kind, label, body, summary, signals, sha256)
values
  ($k$scoring$k$, $k$shared$k$, $k$The scale, and what agreement means$k$, $k$# The scale, and what agreement means

Every score is a whole number from 0 to 100, for **one service at one
business**. It answers one question:

> How strong is the case for writing to this business about this service?

It is not a probability of a sale, and it is not a judgement of the business.

| Score | What has to be true |
|---|---|
| 80–100 | Their own page shows the problem this service fixes, in their own words, and the business is the size and kind we sell to. A quote carries it. |
| 60–79 | Something observed — a quote from their page, or a register fact that could only be read one way — makes the need likely, and nothing argues against it. |
| 40–59 | Plausible and worth one question on a call. The sector and the register suggest it; nothing on their page shows it. |
| 20–39 | Only the sector suggests it, or something on the page argues against it. Not worth a letter on its own. |
| 0–19 | No case. The honest answer is "not this service". |

## The rules every agent is held to in code

- **A score must cite signals.** A proposal that names no signal, or names one
  that was not agreed in the research review, is refused and does not count as
  a proposal.
- **A score is only decided by agreement.** The sales agent and the specialist
  each propose a number. It is settled when one of them accepts the other's
  last number exactly. "Close enough" is not agreement; say the number.
- **No agreement, no score.** If the rounds run out, the service is recorded as
  disputed and the lead gets no number for it. A person reads the argument.
- **A specialist may hand a lead on.** If the signals are really about another
  service, say which and why; the sales agent decides whether to bring that
  specialist in.
- **Nobody invents a contact route.** No email address, phone number, web
  address or postcode appears in anything an agent says. A message that carries
  one is refused whole.

## Arguing well

Say what you think and why, in plain sentences, to the agent you are talking
to. Point at signals by their id. If the other agent is right, say so and take
their number — agreeing quickly with a good argument is the job, not a defeat.
If they are wrong, say which signal they have misread.
$k$, null, null, '3715aca34af5017eeb8e46deef30ce1a3e47f95a3b26526a32b8e5f12c727af8'),
  ($k$who-we-sell-to$k$, $k$shared$k$, $k$Who we sell to$k$, $k$# Who we sell to

Condensed from `business/01-positioning/ideal-customer-profile.md` and
`positioning-statement.md`. Those are the authority; this is what the agents
carry.

n.abl is a small technology consultancy with people in Nottingham and Alcester.
We diagnose one expensive, specific problem in a small business and build the
most appropriate fix: automation, data and reporting, custom software, web, and
AI where it genuinely earns its place. AI is one tool among several. If the
answer is not AI, the client gets the boring version and pays less.

## The business we are looking for

An owner-run business of roughly 5 to 25 people, running on spreadsheets and
email, with at least one process that visibly costs it a day a week or more,
and a director who can say yes on their own.

## Where

Core: Nottingham and the towns around it (Beeston, West Bridgford, Arnold,
Carlton, Hucknall, Long Eaton, Ilkeston and so on), and Alcester and the towns
around it (Studley, Redditch, Bidford-on-Avon, Henley-in-Arden,
Stratford-upon-Avon). Edge towns are worth a letter only when the fit is
otherwise strong.

## What we can and cannot see from outside

Everything an agent knows about a business comes from two places: the public
register (what kind of company, how old, what it says it does, how it files its
accounts, how many directors it has) and the business's own website, if one was
found and confirmed to be theirs.

Neither tells you whether anyone inside will actually want the thing. That is
learned on a call. So every judgement here is a **hypothesis about where a
conversation would start**, never a qualification.

## Honest signs a business is not for us

- It is dormant, a holding company, or a property-owning vehicle with no staff.
- It is one person working alone with nothing to automate but their own diary.
- It is large enough to have an IT department — they will not hire two people
  from Alcester, and should not.
- It is itself a software, web or IT business. We would be selling to a
  competitor.
$k$, null, null, '462792dbc2d73bb92c1b469423993fd3407345bcfd0b20a7ab5cd7bc83bcb159'),
  ($k$ai$k$, $k$service$k$, $k$AI$k$, $k$# AI

Grounded in `business/01-positioning/positioning-statement.md` (AI is one tool
among several) and `saying-no.md` §3.1.

## In one paragraph

A model doing a job a person was doing: reading, drafting, classifying,
answering. Only where the work is genuinely language or judgement, never as
decoration. Document handling (pulling what matters out of forms, letters and
PDFs), classifying incoming work, assistants that answer the same questions
customers ask every day, drafting from records the business already holds. If
ordinary code can do it, it is not an AI job, and we say so.

## Signals that point here

- High inbound volume of written enquiries that ask the same few things:
  public-facing businesses with FAQs, opening times, pricing questions,
  eligibility questions.
- Documents arriving in volume that a person reads and rekeys: applications,
  claims, referrals, CVs, delivery notes, supplier invoices in many formats.
- Drafting that repeats: reports, letters, proposals, care notes, inspection
  write-ups assembled from notes.
- A professional practice (legal, accounting, recruitment, property) whose work
  is reading and summarising.

## Signals that point somewhere else

- The task is moving fields from one system to another in a fixed shape →
  **automation**. Code, not a model. Checking things is always code.
- The question is about the business's own figures → **data_analytics**.
- They want "an AI strategy" → not a job we take; `saying-no.md` §3.1.

## What we would build

Document extraction into structured records; classification and routing of
incoming email or forms; a customer-facing assistant grounded in their own
information, with a person behind it; drafting tools that start from records
the business holds; internal search across their own documents. Always with a
person checking anything that leaves the building.

## What kills it

- The job is really deterministic — a rule, a lookup, a comparison. A model
  that is usually right is worse than code that is always right.
- The documents are personal or special-category data they have no lawful
  basis to put through a third-party model.
- Nobody inside will check the output.

## How this specialist scores

Be the sceptic in the room. AI is the service most likely to be proposed for
the wrong reason. A sector that "could use a chatbot" is 30 at most. 60 or more
needs observed volume of language work: many enquiries, many documents, their
own words about reading, answering or writing the same things repeatedly. 80
or more needs that plus a task where a wrong answer is caught before it causes
harm.

If the signals would be better served by automation, say so to the sales agent
and hand the lead on rather than scoring it here.

## The question that settles it

"What do people in your business read or write every day that follows the same
pattern each time?"
$k$, $k$A model doing a job a person was doing: reading, drafting, classifying,
answering. Only where the work is genuinely language or judgement, never as
decoration. Document handling (pulling what matters out of forms, letters and
PDFs), classifying incoming work, assistants that answer the same questions
customers ask every day, drafting from records the business already holds. If
ordinary code can do it, it is not an AI job, and we say so.$k$, $k$- High inbound volume of written enquiries that ask the same few things:
  public-facing businesses with FAQs, opening times, pricing questions,
  eligibility questions.
- Documents arriving in volume that a person reads and rekeys: applications,
  claims, referrals, CVs, delivery notes, supplier invoices in many formats.
- Drafting that repeats: reports, letters, proposals, care notes, inspection
  write-ups assembled from notes.
- A professional practice (legal, accounting, recruitment, property) whose work
  is reading and summarising.$k$, '55f58d748f084a7558825818b901b82790eb192d19f3efeaca7a4ad16b47d143'),
  ($k$automation$k$, $k$service$k$, $k$Automation$k$, $k$# Automation

Grounded in `business/01-positioning/service-categories.md` §1 (Save time) and
§2 (Reduce mistakes), which is where most automation work comes from.

## In one paragraph

Take repetitive work off people's hands. Something happens on its own that a
person was doing by hand: a form that files itself, a report that arrives, two
systems that start talking, a reminder that goes out before a renewal lapses.
The problem is nearly always a person moving information from one place to
another — between two systems, between an email and a spreadsheet, between
paper and all three — or assembling the same document by hand from parts that
already exist.

## Signals that point here

- A process described on their own page that plainly involves a person doing it
  by hand: "email us your form and we will add you", "download, fill in and
  return", "we will call you back to confirm".
- A PDF form, a Word document to download, or "print and post" where the
  business then has to rekey what comes back.
- Recurring deadlines they manage for customers or themselves: renewals,
  certificates, inspections, MOTs, service intervals, compliance dates.
- Several systems named on the page (an accounts package, a booking tool, a
  shop) with nothing suggesting they talk to each other.
- Volume that repeats: many small jobs, many invoices, many bookings a week.
- Accounts filed as a small or micro company, with several directors or an
  obvious team: big enough to have admin, too small for an IT department.

## Signals that point somewhere else

- The problem is a customer who cannot book or pay online → **web**.
- They hold figures they cannot answer questions with, and the question is
  about the business rather than a task → **data_analytics**.
- Nothing off the shelf fits the way they work and the job is a new tool, not a
  faster old one → **software**.
- The task is reading, sorting or drafting free text at volume → **ai**, but
  only if code cannot do it; say so if it can.

## What we would build

Quote and estimate generators; documents generated from a template and filed
automatically; scheduled data movement between systems with failures reported
to a person; spreadsheet-to-database moves where a spreadsheet has become the
operating system; recurring reports produced on a schedule; email triage and
routing from a shared inbox; job sheet and timesheet capture from a phone;
expiry and renewal tracking; cross-checks (invoice against delivery note, order
against despatch) that flag only the exceptions.

## What kills it

Learned on a call, never from a website — write it down so the call asks:

- They will not let us watch the task being done.
- The measured saving comes out under about £1,000 a year.
- They are mid-migration to a new system that replaces the process anyway.
- They can name the person who makes the mistakes but not the process that
  allows them.

## How this specialist scores

Start from what the page shows a person doing by hand, not from the sector. A
sector that "usually" has admin is a 40 at most on its own. A quoted manual step
on their own page ("send us the completed form by email") with a business big
enough for it to repeat is 60 or more. A quoted manual step that plainly repeats
many times a week, in a business with staff, is 80 or more.

Mark down when the page shows the process is already automated (an online form
that clearly lands in a system, a customer portal, integrations named). Mark
down hard for a sole trader: there is nobody to give the time back to.

## The question that settles it

"Which job takes somebody a day or more every month, and can I watch it being
done once?"
$k$, $k$Take repetitive work off people's hands. Something happens on its own that a
person was doing by hand: a form that files itself, a report that arrives, two
systems that start talking, a reminder that goes out before a renewal lapses.
The problem is nearly always a person moving information from one place to
another — between two systems, between an email and a spreadsheet, between
paper and all three — or assembling the same document by hand from parts that
already exist.$k$, $k$- A process described on their own page that plainly involves a person doing it
  by hand: "email us your form and we will add you", "download, fill in and
  return", "we will call you back to confirm".
- A PDF form, a Word document to download, or "print and post" where the
  business then has to rekey what comes back.
- Recurring deadlines they manage for customers or themselves: renewals,
  certificates, inspections, MOTs, service intervals, compliance dates.
- Several systems named on the page (an accounts package, a booking tool, a
  shop) with nothing suggesting they talk to each other.
- Volume that repeats: many small jobs, many invoices, many bookings a week.
- Accounts filed as a small or micro company, with several directors or an
  obvious team: big enough to have admin, too small for an IT department.$k$, '19321202ff130dd2278159a0e403ed9d188b6ed1b3925ed52938d00d26308c86'),
  ($k$data_analytics$k$, $k$service$k$, $k$Data & Analytics$k$, $k$# Data & Analytics

Grounded in `business/01-positioning/service-categories.md` §3 (Understand your
data).

## In one paragraph

They hold information they cannot answer questions with. Almost never a "big
data" problem: the numbers exist, they live in three or four places that
disagree, and assembling them by hand costs somebody a day a month — so it
happens late or not at all, and decisions get made on memory. The work is
getting it into one place, making it trustworthy, and making it answer the
question somebody actually asks. Start with the decision, not the data.

## Signals that point here

- Several places the same facts live, visible from outside: an online shop and
  a shop floor, several branches or sites, an accounts package and a separate
  booking system.
- A business whose margins depend on knowing which jobs pay: contractors,
  trades with many small jobs, wholesalers, manufacturers, agencies billing
  time.
- Stock, fleet, plant or assets mentioned in volume.
- Several years of trading with a growing team or several sites — the point at
  which "I know roughly how we are doing" stops being true.
- Accounts filed as small rather than micro: enough activity for the numbers to
  matter and to be spread across systems.

## Signals that point somewhere else

- The numbers are fine and one person retypes them between two systems →
  **automation**.
- They want customers to see their own records → **web** or **software**.
- The underlying records do not exist yet; the first job is capturing them →
  **software** or **automation**, and say so.

## What we would build

Data cleaning and reconciliation so a customer, product or job means the same
thing everywhere; one dataset assembled on a schedule from the systems already
in use; reporting that builds itself overnight; dashboards only where a live
view changes a decision — otherwise a scheduled email with five numbers;
job-level profitability and utilisation; spreadsheets done properly, which is
often the right answer.

## What kills it

- The underlying data does not exist, or nobody will own its accuracy.
- They want a dashboard because a competitor has one — no decision attached.
- The answer already sits in a report they own and do not open.

## How this specialist scores

The page rarely shows this problem directly, so be honest about that: most
leads here are a 40–59 on sector, size and structure. Go to 60 or more only when
something observed shows the data is split or the decisions depend on it —
several branches or channels named on their own page, stock or fleet in
volume, a register fact that shows real scale. 80 or more needs their own words
about reporting, figures, visibility or "knowing where we are".

A business too small to have more than one system is under 30: there is nothing
to join up.

## The question that settles it

"What decision would you make differently next month if you had a better answer
to it — and where do the numbers for it live now?"
$k$, $k$They hold information they cannot answer questions with. Almost never a "big
data" problem: the numbers exist, they live in three or four places that
disagree, and assembling them by hand costs somebody a day a month — so it
happens late or not at all, and decisions get made on memory. The work is
getting it into one place, making it trustworthy, and making it answer the
question somebody actually asks. Start with the decision, not the data.$k$, $k$- Several places the same facts live, visible from outside: an online shop and
  a shop floor, several branches or sites, an accounts package and a separate
  booking system.
- A business whose margins depend on knowing which jobs pay: contractors,
  trades with many small jobs, wholesalers, manufacturers, agencies billing
  time.
- Stock, fleet, plant or assets mentioned in volume.
- Several years of trading with a growing team or several sites — the point at
  which "I know roughly how we are doing" stops being true.
- Accounts filed as small rather than micro: enough activity for the numbers to
  matter and to be spread across systems.$k$, '551a8a14bd6a2450ecebfb9230f8f895179230f55ae1ebfcaac49be9cfb0e1ea'),
  ($k$software$k$, $k$service$k$, $k$Custom Software$k$, $k$# Custom Software

Grounded in `business/01-positioning/service-categories.md` §4 (Build
something new).

## In one paragraph

A tool that does not exist and has to be built, because nothing off the shelf
fits the way this business works: an internal tool that replaces the shared
spreadsheet nobody is allowed to touch, a client portal, a field app for job
sheets and sign-off on site, a register for stock, assets, plant or documents.
We check for the off-the-shelf answer first and say so if it exists — losing a
build and gaining a client who trusts us is a good trade.

## Signals that point here

- A workflow described on their page that is specific to their trade and
  unlikely to be served by a generic product: inspections with certificates,
  multi-stage jobs, bespoke quoting rules.
- Customers who need to see their own documents, certificates, jobs or history
  ("we will email you your certificate", "call us for an update on your job").
- Field work: engineers, installers, surveyors, cleaners, carers — anyone whose
  record of the job is made away from a desk.
- Regulated record-keeping where a spreadsheet is the current answer and an
  audit trail would matter.
- A business that has grown through several years and several directors while
  still visibly running on email and forms.

## Signals that point somewhere else

- The need is public-facing — booking, buying, enquiring → **web**.
- The same tool exists off the shelf and they simply are not using it →
  not ours to build; say so (training and support, which this pipeline does not
  score).
- An existing process is being made faster rather than a new capability built →
  **automation**.

## What we would build

Client portals; internal tools and staff dashboards; booking and scheduling
where the constraints are real; mobile-friendly field applications (job
sheets, inspection forms, photo capture, sign-off); registers for stock,
assets, plant, vehicles and documents; customer-facing document delivery with
private storage and short-lived links rather than attachments.

## What kills it

- They will not answer "what happens on the day it does not exist?"
- A finished specification and a request for a price only.
- The build is a product venture to sell to their industry rather than a need
  of their own business.

## How this specialist scores

Custom software is the most expensive thing we sell and the easiest to
over-sell. A sector that "could use an app" is 30 at most. 60 or more needs an
observed workflow that generic tools handle badly — their own words describing
certificates, site visits, multi-step jobs or customers chasing updates. 80 or
more needs that plus evidence the business is large enough to pay for a build:
several directors or staff, several years trading, accounts beyond micro.

Mark down when the page already shows a portal or a named industry product
doing the job.

## The question that settles it

"What do you do today instead of having this, and who does it?"
$k$, $k$A tool that does not exist and has to be built, because nothing off the shelf
fits the way this business works: an internal tool that replaces the shared
spreadsheet nobody is allowed to touch, a client portal, a field app for job
sheets and sign-off on site, a register for stock, assets, plant or documents.
We check for the off-the-shelf answer first and say so if it exists — losing a
build and gaining a client who trusts us is a good trade.$k$, $k$- A workflow described on their page that is specific to their trade and
  unlikely to be served by a generic product: inspections with certificates,
  multi-stage jobs, bespoke quoting rules.
- Customers who need to see their own documents, certificates, jobs or history
  ("we will email you your certificate", "call us for an update on your job").
- Field work: engineers, installers, surveyors, cleaners, carers — anyone whose
  record of the job is made away from a desk.
- Regulated record-keeping where a spreadsheet is the current answer and an
  audit trail would matter.
- A business that has grown through several years and several directors while
  still visibly running on email and forms.$k$, 'e3046844155fa7d83d7d8d4657ce8af2aea5dcc00163e15c7c01af18ddab4a79'),
  ($k$web$k$, $k$service$k$, $k$Web$k$, $k$# Web

Grounded in `business/01-positioning/service-categories.md` §4 (websites,
booking, portals) and the site's own "What we build" section.

## In one paragraph

The public-facing thing: a site, a booking flow, a portal, a payment, a form
that reaches the right person. What a customer touches. Not a brochure for the
sake of one — a website is worth building when it takes work off the business:
the booking that no longer needs a phone call, the enquiry that arrives with
everything needed to answer it, the payment taken up front.

## Signals that point here

- No website at all, or a social page doing the job of one, for a business
  whose customers plainly look them up first.
- A brochure site where the only call to action is "call us" or "email us",
  for a business that takes bookings, appointments or orders.
- A placeholder, parked or broken site under a domain that is clearly theirs.
- Visible age: copyright years long past, no mobile layout, "under
  construction".
- Booking, appointment, order or quote language on the page with no way to do
  any of it online.

## Signals that point somewhere else

- Online booking already exists and the problem is behind it (rekeying into
  the diary, chasing confirmations) → **automation**.
- They need customers to log in to their own records → **software** (a portal
  is a build, even when it lives on the website).
- The page is fine; the question is what the traffic or sales figures mean →
  **data_analytics**.

## What we would build

Websites where the site is the actual requirement; booking flows with payment
and calendar sync; enquiry forms that route to the right person with the right
information; customer portals where customers see their own documents; payment
pages; document delivery that replaces email attachments.

## What kills it

- The business gets all its work through referral and does not want more
  enquiries — a better site solves nothing they have.
- They have just paid someone else for a new site.
- The request is a redesign for its own sake, with no job attached to it.

## How this specialist scores

The web is the one service where the evidence is almost always observable, so
hold it to that. No site at all, for a customer-facing business, is 50–65: the
need is plausible but we cannot see whether they want more work. A site that
shows booking or ordering language with no way to transact is 65–80. A site
that is broken, parked or obviously abandoned under their own name, with a
business clearly still trading, is 75 or more.

A working transactional site is under 25 for web — look for what sits behind
it instead and hand on.

## The question that settles it

"When a new customer finds you, what do they have to do before you can help
them — and which part of that do you do by hand?"
$k$, $k$The public-facing thing: a site, a booking flow, a portal, a payment, a form
that reaches the right person. What a customer touches. Not a brochure for the
sake of one — a website is worth building when it takes work off the business:
the booking that no longer needs a phone call, the enquiry that arrives with
everything needed to answer it, the payment taken up front.$k$, $k$- No website at all, or a social page doing the job of one, for a business
  whose customers plainly look them up first.
- A brochure site where the only call to action is "call us" or "email us",
  for a business that takes bookings, appointments or orders.
- A placeholder, parked or broken site under a domain that is clearly theirs.
- Visible age: copyright years long past, no mobile layout, "under
  construction".
- Booking, appointment, order or quote language on the page with no way to do
  any of it online.$k$, '80b41ae7529ab02d569a6df1aac3a030af7c32b5944c33df005fe9f8db98f535')
on conflict (key) do update
   set kind = excluded.kind, label = excluded.label, body = excluded.body,
       summary = excluded.summary, signals = excluded.signals,
       sha256 = excluded.sha256, active = true, updated_at = now();

-- A folder that was removed stops being a service the agents may argue for.
update public.prospect_knowledge
   set active = false, updated_at = now()
 where key not in ('scoring', 'who-we-sell-to', 'ai', 'automation', 'data_analytics', 'software', 'web');
